server:
  port: 8080
  servlet:
    context-path: /e-learning

spring:
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
  application:
    name: K-English
  datasource:
    url: jdbc:postgresql://localhost:5432/ELearning
    username: postgres
    password: 291104
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  refreshKey: ${JWT_REFRESH_KEY}
  resetKey: ${JWT_RESET_KEY}
  confirmKey: ${JWT_CONFIRM_KEY}
  expiryHour: ${JWT_EXPIRY_HOUR:1}
  expiryDay: ${JWT_EXPIRY_DAY:3}
  expiryMinute: ${JWT_EXPIRY_MINUTE:30}
